INSERT INTO TAMANHO (NOME, QUANTIDADE) VALUES ('pequeno', 300)
INSERT INTO TAMANHO (NOME, QUANTIDADE) VALUES ('medio', 500)
INSERT INTO TAMANHO (NOME, QUANTIDADE) VALUES ('grande', 700)

INSERT INTO FRUTA (NOME, TEMPO_ADICIONAL) VALUES ('morango', NULL)
INSERT INTO FRUTA (NOME, TEMPO_ADICIONAL) VALUES ('banana', NULL)
INSERT INTO FRUTA (NOME, TEMPO_ADICIONAL) VALUES ('kiwi', 5)

INSERT INTO ADICIONAL (NOME, VALOR, TEMPO_ADICIONAL) VALUES ('leite ninho', 3, NULL)
INSERT INTO ADICIONAL (NOME, VALOR, TEMPO_ADICIONAL) VALUES ('granola', NULL , NULL)
INSERT INTO ADICIONAL (NOME, VALOR, TEMPO_ADICIONAL) VALUES ('paçoca', 3, 3)