INSERT INTO TAMANHO (ID, NOME, QUANTIDADE, VALOR, TEMPO_ADICIONAL) VALUES (1, 'pequeno', 300, 10.0, 5)
INSERT INTO TAMANHO (ID, NOME, QUANTIDADE, VALOR, TEMPO_ADICIONAL) VALUES (2, 'medio', 500, 13.0, 7)
INSERT INTO TAMANHO (ID, NOME, QUANTIDADE, VALOR, TEMPO_ADICIONAL) VALUES (3, 'grande', 700, 15.0, 15)

INSERT INTO FRUTA (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (1, 'morango', NULL, NULL)
INSERT INTO FRUTA (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (2, 'banana', NULL, NULL)
INSERT INTO FRUTA (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (3, 'kiwi', NULL, 5)

INSERT INTO TIPO_ADICIONAL (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (1, 'leite ninho', 3, NULL)
INSERT INTO TIPO_ADICIONAL (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (2, 'granola', NULL , NULL)
INSERT INTO TIPO_ADICIONAL (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (3, 'paçoca', 3, 3)