INSERT INTO TAMANHO (ID, NOME, QUANTIDADE) VALUES (1, 'pequeno', 300)
INSERT INTO TAMANHO (ID, NOME, QUANTIDADE) VALUES (2, 'medio', 500)
INSERT INTO TAMANHO (ID, NOME, QUANTIDADE) VALUES (3, 'grande', 700)

INSERT INTO FRUTA (ID, NOME, TEMPO_ADICIONAL) VALUES (1, 'morango', NULL)
INSERT INTO FRUTA (ID, NOME, TEMPO_ADICIONAL) VALUES (2, 'banana', NULL)
INSERT INTO FRUTA (ID, NOME, TEMPO_ADICIONAL) VALUES (3, 'kiwi', 5)

INSERT INTO TIPO_ADICIONAL (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (1, 'leite ninho', 3, NULL)
INSERT INTO TIPO_ADICIONAL (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (2, 'granola', NULL , NULL)
INSERT INTO TIPO_ADICIONAL (ID, NOME, VALOR, TEMPO_ADICIONAL) VALUES (3, 'paçoca', 3, 3)