CREATE TABLE TAMANHO (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    QUANTIDADE INT
);

CREATE TABLE FRUTA (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    TEMPO_ADICIONAL INT
);

CREATE TABLE ADICIONAL (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    VALOR INT,
    TEMPO_ADICIONAL INT
);

