CREATE TABLE TAMANHO (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    VALOR DOUBLE,
    TEMPO_ADICIONAL INT,
    QUANTIDADE INT
);

CREATE TABLE FRUTA (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    VALOR DOUBLE,
    TEMPO_ADICIONAL INT
);

CREATE TABLE TIPO_ADICIONAL (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    VALOR DOUBLE,
    TEMPO_ADICIONAL INT
);

CREATE TABLE ACAI (
    ID INT NOT NULL PRIMARY KEY,
    TAMANHO_ID INT,
    FRUTA_ID INT
);

CREATE TABLE ADICIONAL (
    ACAI_ID INT NOT NULL,
    TIPO_ADICIONAL_ID INT NOT NULL,
    FOREIGN KEY (ACAI_ID) REFERENCES ACAI(ID),
    FOREIGN KEY (TIPO_ADICIONAL_ID) REFERENCES TIPO_ADICIONAL(ID)
);